### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by H357753** [mithrand0/reactive-drop-linux-server#6]
Hello, bro.
I'm having problems using.First, did you modify the environment variables in compose when setting up the server?
Secondly, the workshop.cfg file in the creative workshop says that the console cannot be found.
Could you please write the readme file in more detail? Thanks.

**Comment by H357753** [comment]
Like, how can I enable the server.cfg? I think it's better to control my server. Thanks.

**Comment by mithrand0** [comment]
> I'm having problems using.First, did you modify the environment variables in compose when setting up the server?

No, it runs fine out of the box.

If you want to customize a server variable, you can use an environment variable as mentioned in the readme:

> _Any configuration parameters starting with `rd_` with be written as config, i.e. `rd_rcon_password=test` will be `rcon_password test` in the server config._

> Secondly, the workshop.cfg file in the creative workshop says that the console cannot be found.

The Steam download doesn't include a workshop.cfg. If you want to create one, you can mount the game folder on your system using a standard docker volume mount:

```
    volumes:
      - "./data/reactivedrop:/usr/lib/games/reactivedrop"
```

The game will be in `data/reactivedrop` then.

Since this is not really a bug, closing the ticket.
